#!/bin/sh

set -e

git branch -f nightly @
git push -f origin nightly

# create a git hook for this repo
# that will auto-run this goodnight.sh script
# after a stacked-rebase is finished in this repo.
POST_STACKED_REBASE_HOOK_PATH=".git/hooks/post-stacked-rebase"

cat > "$POST_STACKED_REBASE_HOOK_PATH" <<'EOF'
#!/bin/sh

# DO NOT EDIT THIS FILE MANUALLY
# AUTO-GENERATED BY GIT-STACKED-REBASE's goodnight.sh script.

DIRNAME="$(dirname $0)"

GOODNIGHT_SCRIPT="$(realpath $DIRNAME/../../goodnight.sh)"

sh "$GOODNIGHT_SCRIPT"
EOF

chmod +x "$POST_STACKED_REBASE_HOOK_PATH"
