import fs from "fs";
import path from "path";

/**
 * installs a "wrapper" hook that will allow the user
 * to have as many scripts for the hook as needed:
 *
 * the user just needs to create more scripts
 * with the "<hook-name>.<purpose>" filename format,
 * e.g. `post-rewrite.git-stacked-rebase`
 *
 */
export function setupHookWrapper(hookName: string, dotGitDirPath: string): void {
	const needle = "NEEDLE__WRAPPER_HOOK";
	const version = 0;

	const scriptContent = `\
#!/bin/sh

# DO NOT EDIT THIS FILE MANUALLY
# AUTO-GENERATED BY GIT-STACKED-REBASE

# ${needle} ${version}

for script in $(find . -name "${hookName}.*"); do
	sh "$script"
done`;

	const hooksDir: string = path.join(dotGitDirPath, "hooks");
	const pathToHookScript: string = path.join(hooksDir, hookName);

	fs.mkdirSync(hooksDir, { recursive: true });
	renameCustomScriptIfExists();
	fs.writeFileSync(pathToHookScript, scriptContent, { mode: "777" });

	/**
	 * prerequisite:
	 * if a user has an existing custom post-rewrite script,
	 * rename it to a different name, so that:
	 * 1. we can use the `post-rewrite` filename for ourselves,
	 * 2. the custom, now renamed, script, will still be called by us.
	 */
	function renameCustomScriptIfExists(): void {
		const fileExists = fs.existsSync(pathToHookScript);
		const fileContent = !fileExists ? "" : fs.readFileSync(pathToHookScript, { encoding: "utf-8" });
		const userHasCustomScript: boolean = fileExists && !fileContent.includes(needle);

		if (userHasCustomScript) {
			const newPath = pathToHookScript + ".custom." + Math.random();
			fs.renameSync(pathToHookScript, newPath);

			const filename = path.basename(newPath);
			const msg = `\ninfo: moved custom "post-rewrite" script into "${filename}", will still be called.\n\n`;
			process.stdout.write(msg);
		}
	}
}

export function setupPostRewriteHookFor(suffix: string, dotGitDirPath: string): void {
	const hooksDir: string = path.join(dotGitDirPath, "hooks");
	const pathToPostRewriteScript: string = path.join(hooksDir, "post-rewrite." + suffix);

	/**
	 * goal is to save the rewritten-list file,
	 * which git deletes once the rebase is done,
	 *
	 * and when git-stacked-rebase gets called again
	 * with `--apply` or whatever - to recover the commits.
	 *
	 */

	const needle = "NEEDLE__GIT_STACKED_REBASE";

	const postRewriteScript: string = `\
#!/bin/sh

# DO NOT EDIT THIS FILE MANUALLY
# AUTO-GENERATED BY GIT-STACKED-REBASE

# ${needle}

DOT_GIT_DIR="$(git rev-parse --absolute-git-dir)"
STACKED_REBASE_DIR="$DOT_GIT_DIR/stacked-rebase"
REWRITTEN_LIST_BACKUP_FILE_PATH="$STACKED_REBASE_DIR/rewritten-list"

mkdir -p "$STACKED_REBASE_DIR"

cat >> "$REWRITTEN_LIST_BACKUP_FILE_PATH" <<EOF
$1
$(cat /dev/stdin)

EOF

# note that the this format of the message matters
# because we later decode it in 'combineRewrittenLists'.

`;

	fs.writeFileSync(pathToPostRewriteScript, postRewriteScript, { mode: "777" });
}
