name: "tests"

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-preventing-a-specific-failing-matrix-job-from-failing-a-workflow-run
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        node: [12, 14, 16, 18]
        experimental: [false]
        exclude:
          - os: macos-latest
            node: 12

            # nodegit binary missing...
            #
            # e.g. https://github.com/kiprasmel/git-stacked-rebase/actions/runs/4606760208/jobs/8140453365
            #
            # ```
            # install response status 404 Not Found on
            # https://axonodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.28.0-alpha.18-node-v108-linux-x64.tar.gz
            # ```
            #
            # see also:
            # - https://github.com/nodegit/nodegit/issues/1840#issuecomment-943083741
            # - https://github.com/nodegit/nodegit/issues/1840#issuecomment-1302139622
          - os: ubuntu-latest
            node: 18
        include:
          # test macos - for some reason, internet conn fails @ github actions
          - os: macos-latest
            node: 12
            experimental: true

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'
      - run: yarn --frozen-lockfile
      - run: yarn test
 